// Hand-written starter course: units of words and phrases/sentences, plus short beginner dialogues.
// Everything here is kept to common, short, high-certainty Yoruba. It still needs a native speaker's review
// (see README): use "Ask a question" in the app to double-check anything that looks off.
// Strings are normalised to NFC on load (ẹ̀ = ẹ + combining grave), so tone marks and underdots compare reliably.

const nfc = (s) => s.normalize("NFC");

/** word: yo, en, pos, example sentence (ex) + its English (exEn). */
const w = (yo, en, pos, ex, exEn) => ({ yo: nfc(yo), en, pos, ex: nfc(ex), exEn });
/** phrase or sentence: yo, en, optional note. */
const p = (yo, en, note = "") => ({ yo: nfc(yo), en, note });

export const UNITS = [
  {
    id: "greetings", title: "Greetings & politeness", emoji: "👋",
    blurb: "Hello, goodbye, thank you, sorry. Greet by time of day, and use ẹ with people you respect.",
    words: [
      w("káàbọ̀", "welcome", "greeting", "Ẹ káàbọ̀ sí ilé wa.", "Welcome to our home."),
      w("ẹ ṣé", "thank you", "greeting", "Ẹ ṣé púpọ̀.", "Thank you very much."),
      w("jọ̀ọ́", "please", "particle", "Ẹ jọ̀ọ́, ẹ ràn mí lọ́wọ́.", "Please help me."),
      w("pẹ̀lẹ́", "sorry (sympathy); take it easy", "greeting", "Pẹ̀lẹ́ o!", "Sorry! / Take it easy!"),
      w("má bínú", "sorry; excuse me (lit. don't be angry)", "expression", "Má bínú, mi ò gbọ́.", "Sorry, I didn't hear."),
      w("dáadáa", "well; fine", "adverb", "Mo wà dáadáa.", "I am fine."),
      w("bẹ́ẹ̀ni", "yes", "particle", "Bẹ́ẹ̀ni, mo mọ̀.", "Yes, I know."),
      w("rárá", "no", "particle", "Rárá, mi ò fẹ́.", "No, I don't want it."),
      w("orúkọ", "name", "noun", "Orúkọ mi ni Adé.", "My name is Adé."),
      w("àlàáfíà", "peace; well-being", "noun", "Àlàáfíà ni.", "I am well. (lit. it is peace)"),
    ],
    phrases: [
      p("Ẹ káàárọ̀.", "Good morning."),
      p("Ẹ káàsán.", "Good afternoon."),
      p("Ẹ kúùrọ̀lẹ́.", "Good evening."),
      p("Ó dàárọ̀.", "Good night. (lit. until morning)"),
      p("Ó dàbọ̀.", "Goodbye."),
      p("Ẹ káàbọ̀.", "Welcome."),
      p("Báwo ni?", "How are you?"),
      p("Ṣé àlàáfíà ni?", "Are you well?", "Usual reply: Àlàáfíà ni."),
      p("Mo wà dáadáa, ẹ ṣé.", "I am fine, thank you."),
      p("Ẹ ṣé púpọ̀.", "Thank you very much."),
      p("Ẹ jọ̀ọ́.", "Please."),
      p("Má bínú.", "Sorry. / Excuse me."),
      p("Kí ni orúkọ rẹ?", "What is your name?"),
      p("Orúkọ mi ni Adé.", "My name is Adé."),
      p("Inú mi dùn láti pàdé rẹ.", "I am glad to meet you."),
      p("Ẹ kú iṣẹ́.", "Well done. (greeting to someone working)"),
    ],
  },
  {
    id: "pronouns", title: "Pronouns & “to be”", emoji: "🙋",
    blurb: "I, you, he/she, we, they. Three words for “to be”: jẹ́, wà and ni.",
    words: [
      w("mo", "I (before a verb)", "pronoun", "Mo jẹ́ akẹ́kọ̀ọ́.", "I am a student."),
      w("o", "you (one person, informal)", "pronoun", "O jẹ́ ọ̀rẹ́ mi.", "You are my friend."),
      w("ó", "he, she, it", "pronoun", "Ó jẹ́ olùkọ́.", "He/she is a teacher."),
      w("a", "we", "pronoun", "A wà ní ilé.", "We are at home."),
      w("ẹ", "you (plural, or one person you respect)", "pronoun", "Ẹ wá síbí.", "Come here. (to someone you respect, or to several people)"),
      w("wọ́n", "they", "pronoun", "Wọ́n wà ní ọjà.", "They are at the market."),
      w("èmi", "I (emphatic)", "pronoun", "Èmi ni Adé.", "I am Adé."),
      w("ìwọ", "you (emphatic, one person)", "pronoun", "Ìwọ ni ọ̀rẹ́ mi.", "You are my friend."),
      w("òun", "he, she (emphatic)", "pronoun", "Òun ni olùkọ́.", "He/she is the teacher."),
      w("àwa", "we (emphatic)", "pronoun", "Àwa ni ọ̀rẹ́ rẹ.", "We are your friends."),
      w("ẹ̀yin", "you (plural, emphatic)", "pronoun", "Ẹ̀yin ni olùkọ́.", "You are the teachers."),
      w("àwọn", "they (emphatic); marks a plural", "pronoun", "Àwọn ọmọ wà níbí.", "The children are here."),
      w("mi", "my; me", "pronoun", "Ilé mi tóbi.", "My house is big."),
      w("rẹ", "your (one person)", "pronoun", "Ilé rẹ dára.", "Your house is nice."),
      w("rẹ̀", "his, her, its", "pronoun", "Ilé rẹ̀ tóbi.", "His/her house is big."),
      w("wa", "our", "pronoun", "Ilé wa wà níbí.", "Our house is here."),
      w("yín", "your (plural, or someone you respect)", "pronoun", "Ilé yín dára.", "Your house is nice."),
      w("wọn", "their", "pronoun", "Ilé wọn tóbi.", "Their house is big."),
      w("jẹ́", "to be (a person or thing)", "verb", "Ó jẹ́ olùkọ́.", "He/she is a teacher."),
      w("wà", "to be (somewhere); to exist", "verb", "Mo wà ní ilé.", "I am at home."),
      w("ni", "it is… (identifies or stresses)", "particle", "Adé ni orúkọ mi.", "Adé is my name."),
      w("àti", "and", "conjunction", "Bàbá àti ìyá wà ní ilé.", "Father and mother are at home."),
      w("olùkọ́", "teacher", "noun", "Olùkọ́ mi dára.", "My teacher is good."),
      w("akẹ́kọ̀ọ́", "student", "noun", "Akẹ́kọ̀ọ́ náà wà níbí.", "The student is here."),
    ],
    phrases: [
      p("Mo jẹ́ akẹ́kọ̀ọ́.", "I am a student."),
      p("Ó jẹ́ olùkọ́.", "He/she is a teacher."),
      p("Mo wà ní ilé.", "I am at home."),
      p("A wà níbí.", "We are here."),
      p("Wọ́n wà níbẹ̀.", "They are there."),
      p("Ẹ wà níbí.", "You (pl.) are here."),
      p("Èmi ni Adé.", "I am Adé."),
      p("Ìwọ ni ọ̀rẹ́ mi.", "You are my friend."),
      p("Ibo ni o wà?", "Where are you?"),
      p("Ṣé ìwọ ni Tọ́lá?", "Are you Tọ́lá?"),
    ],
  },
  {
    id: "family", title: "Family", emoji: "👨‍👩‍👧",
    blurb: "Parents, children, brothers and sisters, friends.",
    words: [
      w("ìdílé", "family; household", "noun", "Ìdílé mi tóbi.", "My family is big."),
      w("bàbá", "father", "noun", "Bàbá mi wà ní ilé.", "My father is at home."),
      w("ìyá", "mother", "noun", "Ìyá mi ń sè oúnjẹ.", "My mother is cooking food."),
      w("ọmọ", "child", "noun", "Mo ní ọmọ méjì.", "I have two children."),
      w("ọkọ", "husband", "noun", "Ọkọ mi wà níbí.", "My husband is here."),
      w("ìyàwó", "wife", "noun", "Ìyàwó rẹ̀ dára.", "His wife is nice."),
      w("arákùnrin", "brother", "noun", "Arákùnrin mi ń bọ̀.", "My brother is coming."),
      w("arábìnrin", "sister", "noun", "Arábìnrin mi jẹ́ olùkọ́.", "My sister is a teacher."),
      w("ẹ̀gbọ́n", "older brother or sister", "noun", "Ẹ̀gbọ́n mi ń gbé ní Èkó.", "My older sibling lives in Lagos."),
      w("àbúrò", "younger brother or sister", "noun", "Àbúrò mi wà ní ilé-ìwé.", "My younger sibling is at school."),
      w("ọ̀rẹ́", "friend", "noun", "Ọ̀rẹ́ mi dára.", "My friend is nice."),
      w("ìyá àgbà", "grandmother", "noun", "Ìyá àgbà mi ń gbé ní abúlé.", "My grandmother lives in a village."),
      w("bàbá àgbà", "grandfather", "noun", "Bàbá àgbà mi wà ní ilé.", "My grandfather is at home."),
      w("ọmọbìnrin", "girl; daughter", "noun", "Ọmọbìnrin náà dára.", "The girl is nice."),
      w("ọmọkùnrin", "boy; son", "noun", "Ọmọkùnrin náà wà níbí.", "The boy is here."),
    ],
    phrases: [
      p("Ìdílé wa tóbi.", "Our family is big."),
      p("Ṣé o ní arákùnrin?", "Do you have a brother?"),
      p("Mo ní arábìnrin kan.", "I have one sister."),
      p("Bàbá mi àti ìyá mi wà ní ilé.", "My father and my mother are at home."),
      p("Ọmọ mélòó ni o ní?", "How many children do you have?"),
      p("Mo ní ọmọ mẹ́ta.", "I have three children."),
      p("Ọ̀rẹ́ mi ni.", "He/she is my friend."),
      p("Ẹ̀gbọ́n mi jẹ́ dókítà.", "My older sibling is a doctor."),
    ],
  },
  {
    id: "numbers", title: "Numbers", emoji: "🔢",
    blurb: "Counting 1–10 and bigger round numbers. With nouns, the number changes form (ọ̀kan → kan, èjì → méjì).",
    words: [
      w("ọ̀kan", "one (counting)", "number", "Mo ní ọmọ kan.", "I have one child."),
      w("èjì", "two (counting)", "number", "Mo ní ọmọ méjì.", "I have two children."),
      w("ẹ̀ta", "three (counting)", "number", "Mo ní ọmọ mẹ́ta.", "I have three children."),
      w("ẹ̀rin", "four (counting)", "number", "Mo ní ọmọ mẹ́rin.", "I have four children."),
      w("àrún", "five (counting)", "number", "Mo ní ọmọ márùn-ún.", "I have five children."),
      w("ẹ̀fà", "six (counting)", "number", "Mo rà ẹyin mẹ́fà.", "I bought six eggs."),
      w("èje", "seven (counting)", "number", "Mo rà ẹyin méje.", "I bought seven eggs."),
      w("ẹ̀jọ", "eight (counting)", "number", "Mo rà ẹyin mẹ́jọ.", "I bought eight eggs."),
      w("ẹ̀sàn-án", "nine (counting)", "number", "Mo rà ẹyin mẹ́sàn-án.", "I bought nine eggs."),
      w("ẹ̀wá", "ten (counting)", "number", "Mo rà ẹyin mẹ́wàá.", "I bought ten eggs."),
      w("ogún", "twenty", "number", "Mo ní ogún náírà.", "I have twenty naira."),
      w("ọgbọ̀n", "thirty", "number", "Ọgbọ̀n ọmọ wà ní kíláàsì.", "Thirty children are in the class."),
      w("ọgọ́rùn-ún", "one hundred", "number", "Ọgọ́rùn-ún náírà ni.", "It is a hundred naira."),
      w("igba", "two hundred", "number", "Igba náírà ni.", "It is two hundred naira."),
      w("ẹgbẹ̀rún", "one thousand", "number", "Ẹgbẹ̀rún náírà ni.", "It is a thousand naira."),
    ],
    phrases: [
      p("ọmọ kan", "one child", "kan comes after the noun."),
      p("ọmọ méjì", "two children"),
      p("ọmọ mẹ́ta", "three children"),
      p("ọmọ mẹ́rin", "four children"),
      p("ọmọ márùn-ún", "five children"),
      p("ọmọ mẹ́fà", "six children"),
      p("ọmọ méje", "seven children"),
      p("ọmọ mẹ́jọ", "eight children"),
      p("ọmọ mẹ́sàn-án", "nine children"),
      p("ọmọ mẹ́wàá", "ten children"),
      p("Mélòó ni?", "How many?"),
      p("Ọgọ́rùn-ún náírà ni.", "It is a hundred naira."),
    ],
  },
  {
    id: "market", title: "Food & market", emoji: "🧺",
    blurb: "Everyday foods, asking the price, buying and eating.",
    words: [
      w("oúnjẹ", "food", "noun", "Oúnjẹ yìí dùn.", "This food is delicious."),
      w("omi", "water", "noun", "Mo fẹ́ omi.", "I want water."),
      w("ìrẹsì", "rice", "noun", "Mo fẹ́ jẹ ìrẹsì.", "I want to eat rice."),
      w("ẹran", "meat", "noun", "Ṣé o fẹ́ ẹran?", "Do you want meat?"),
      w("ẹja", "fish", "noun", "Mo fẹ́ràn ẹja.", "I like fish."),
      w("ẹyin", "egg", "noun", "Mo rà ẹyin.", "I bought eggs."),
      w("ẹ̀wà", "beans", "noun", "Ẹ̀wà dùn.", "Beans are delicious."),
      w("iṣu", "yam", "noun", "Mo fẹ́ jẹ iṣu.", "I want to eat yam."),
      w("búrẹ́dì", "bread", "noun", "Mo rà búrẹ́dì.", "I bought bread."),
      w("ata", "pepper", "noun", "Ata yìí gbóná.", "This pepper is hot."),
      w("iyọ̀", "salt", "noun", "Mo fẹ́ iyọ̀ díẹ̀.", "I want a little salt."),
      w("ọsàn", "orange", "noun", "Mo fẹ́ ọsàn.", "I want an orange."),
      w("ọjà", "market", "noun", "Mo ń lọ sí ọjà.", "I am going to the market."),
      w("owó", "money", "noun", "Mo ní owó.", "I have money."),
      w("gan-an", "very; really", "adverb", "Oúnjẹ yìí dùn gan-an.", "This food is very delicious."),
      w("díẹ̀", "a little", "adverb", "Mo fẹ́ omi díẹ̀.", "I want a little water."),
      w("púpọ̀", "much; many; a lot", "adverb", "Mo ní owó púpọ̀.", "I have a lot of money."),
    ],
    phrases: [
      p("Èló ni èyí?", "How much is this?"),
      p("Èló ni ìrẹsì?", "How much is the rice?"),
      p("Ó wọ́n jù.", "It is too expensive."),
      p("Mo fẹ́ ra ìrẹsì.", "I want to buy rice."),
      p("Ẹ fún mi ní omi.", "Please give me water."),
      p("Oúnjẹ yìí dùn gan-an.", "This food is very delicious."),
      p("Mo fẹ́ jẹun.", "I want to eat."),
      p("Ṣé o fẹ́ mu omi?", "Do you want to drink water?"),
      p("Mo fẹ́ràn ẹja.", "I like fish."),
    ],
  },
  {
    id: "places", title: "Places & directions", emoji: "🧭",
    blurb: "Where things are, how to get there, and the small words ní, sí and láti.",
    words: [
      w("ilé", "house; home", "noun", "Mo wà ní ilé.", "I am at home."),
      w("ilé-ìwé", "school", "noun", "Ọmọ náà wà ní ilé-ìwé.", "The child is at school."),
      w("ilé-ìwòsàn", "hospital", "noun", "Mo ń lọ sí ilé-ìwòsàn.", "I am going to the hospital."),
      w("ìlú", "town; city", "noun", "Ìlú yìí tóbi.", "This town is big."),
      w("abúlé", "village", "noun", "Ìyá àgbà mi ń gbé ní abúlé.", "My grandmother lives in a village."),
      w("ọ̀nà", "road; way", "noun", "Ọ̀nà náà jìn.", "The road is far."),
      w("ọkọ̀", "vehicle; car", "noun", "Ọkọ̀ náà ń bọ̀.", "The vehicle is coming."),
      w("ibi", "place", "noun", "Ibi yìí dára.", "This place is nice."),
      w("ibo", "where", "question word", "Ibo ni ọjà wà?", "Where is the market?"),
      w("ọ̀tún", "right (side)", "noun", "Yà sí ọ̀tún.", "Turn right."),
      w("òsì", "left (side)", "noun", "Yà sí òsì.", "Turn left."),
      w("tààrà", "straight", "adverb", "Lọ tààrà.", "Go straight."),
      w("níbí", "here", "adverb", "Dúró níbí.", "Stop here."),
      w("níbẹ̀", "there", "adverb", "Ó wà níbẹ̀.", "It is there."),
      w("jìn", "far", "verb", "Ó jìn.", "It is far."),
      w("ní", "in; at; (also) to have", "preposition", "Mo wà ní ọjà.", "I am at the market."),
      w("sí", "to; towards", "preposition", "Mo ń lọ sí ilé.", "I am going home."),
      w("láti", "from", "preposition", "Mo wá láti Èkó.", "I come from Lagos."),
    ],
    phrases: [
      p("Ibo ni ọjà wà?", "Where is the market?"),
      p("Ibo ni ilé-ìwòsàn wà?", "Where is the hospital?"),
      p("Mo ń lọ sí ọjà.", "I am going to the market."),
      p("Lọ tààrà, lẹ́yìn náà yà sí ọ̀tún.", "Go straight, then turn right."),
      p("Yà sí òsì.", "Turn left."),
      p("Dúró níbí.", "Stop here."),
      p("Mo fẹ́ lọ sí ọjà.", "I want to go to the market."),
      p("Mo fẹ́ lọ sí ilé.", "I want to go home."),
      p("Mo wá láti Èkó.", "I come from Lagos."),
    ],
  },
  {
    id: "time", title: "Time & days", emoji: "📅",
    blurb: "Today, tomorrow, parts of the day and the seven days of the week.",
    words: [
      w("ọjọ́", "day", "noun", "Ọjọ́ wo ni òní?", "What day is today?"),
      w("òní", "today", "noun", "Òní ni ọjọ́ ìbí mi.", "Today is my birthday."),
      w("ọ̀la", "tomorrow", "noun", "Mo máa lọ sí ọjà ní ọ̀la.", "I will go to the market tomorrow."),
      w("àná", "yesterday", "noun", "Mo rí ọ ní àná.", "I saw you yesterday."),
      w("àárọ̀", "morning", "noun", "Mo jí ní àárọ̀.", "I wake up in the morning."),
      w("ọ̀sán", "afternoon; daytime", "noun", "Ó gbóná ní ọ̀sán.", "It is hot in the afternoon."),
      w("ìrọ̀lẹ́", "evening", "noun", "Mo wà ní ilé ní ìrọ̀lẹ́.", "I am at home in the evening."),
      w("òru", "night", "noun", "Mo sùn ní òru.", "I sleep at night."),
      w("ọ̀sẹ̀", "week", "noun", "Ọ̀sẹ̀ kan ní ọjọ́ méje.", "A week has seven days."),
      w("oṣù", "month", "noun", "Oṣù yìí gbóná.", "This month is hot."),
      w("ọdún", "year", "noun", "Ọdún tuntun ti dé.", "The new year has arrived."),
      w("wákàtí", "hour", "noun", "Wákàtí kan ni.", "It is one hour."),
      w("nísinsìnyí", "now", "adverb", "Mo wà ní ilé nísinsìnyí.", "I am at home now."),
      w("Ọjọ́ Ajé", "Monday", "noun", "Òní ni Ọjọ́ Ajé.", "Today is Monday."),
      w("Ọjọ́ Ìṣẹ́gun", "Tuesday", "noun", "Òní ni Ọjọ́ Ìṣẹ́gun.", "Today is Tuesday."),
      w("Ọjọ́rú", "Wednesday", "noun", "Òní ni Ọjọ́rú.", "Today is Wednesday."),
      w("Ọjọ́bọ̀", "Thursday", "noun", "Òní ni Ọjọ́bọ̀.", "Today is Thursday."),
      w("Ọjọ́ Ẹtì", "Friday", "noun", "Òní ni Ọjọ́ Ẹtì.", "Today is Friday."),
      w("Ọjọ́ Àbámẹ́ta", "Saturday", "noun", "Òní ni Ọjọ́ Àbámẹ́ta.", "Today is Saturday."),
      w("Ọjọ́ Àìkú", "Sunday", "noun", "Òní ni Ọjọ́ Àìkú.", "Today is Sunday."),
    ],
    phrases: [
      p("Ọjọ́ wo ni òní?", "What day is today?"),
      p("Mo máa rí ọ ní ọ̀la.", "I will see you tomorrow."),
      p("Nígbà wo?", "When?"),
      p("Ó ti pẹ́.", "It is late."),
      p("Mo wá ní àárọ̀.", "I come in the morning."),
      p("Ọdún tuntun ti dé.", "The new year has arrived."),
    ],
  },
  {
    id: "feelings", title: "Feelings & health", emoji: "💛",
    blurb: "How you feel, and what to say when you are hungry, tired or unwell.",
    words: [
      w("ara", "body", "noun", "Ara mi yá.", "I am well. (lit. my body is fine)"),
      w("orí", "head", "noun", "Orí ń fọ́ mí.", "I have a headache."),
      w("ikùn", "stomach", "noun", "Ikùn ń dùn mí.", "My stomach hurts."),
      w("ebi", "hunger", "noun", "Ebi ń pa mí.", "I am hungry."),
      w("òùngbẹ", "thirst", "noun", "Òùngbẹ ń gbẹ mí.", "I am thirsty."),
      w("oorun", "sleep", "noun", "Oorun ń run mí.", "I am sleepy."),
      w("àìsàn", "illness", "noun", "Ó ní àìsàn.", "He/she has an illness."),
      w("oògùn", "medicine", "noun", "Mo fẹ́ oògùn.", "I want medicine."),
      w("dókítà", "doctor", "noun", "Mo fẹ́ rí dókítà.", "I want to see a doctor."),
      w("dùn", "to be sweet, pleasant, or painful", "verb", "Inú mi dùn.", "I am happy."),
      w("dára", "good; fine", "adjective", "Ó dára.", "It is good."),
      w("ayọ̀", "joy", "noun", "Mo ní ayọ̀.", "I am joyful."),
    ],
    phrases: [
      p("Inú mi dùn.", "I am happy."),
      p("Inú bí mi.", "I am angry."),
      p("Ó rẹ̀ mí.", "I am tired."),
      p("Ara mi yá.", "I am well."),
      p("Ara mi kò yá.", "I am not well."),
      p("Ebi ń pa mí.", "I am hungry."),
      p("Òùngbẹ ń gbẹ mí.", "I am thirsty."),
      p("Oorun ń run mí.", "I am sleepy."),
      p("Orí ń fọ́ mí.", "I have a headache."),
      p("Ikùn ń dùn mí.", "My stomach hurts."),
      p("Mo fẹ́ rí dókítà.", "I want to see a doctor."),
      p("Ṣé ara rẹ yá?", "Are you well?"),
    ],
  },
  {
    id: "verbs", title: "Verbs & tense particles", emoji: "⚙️",
    blurb: "Yoruba verbs never change form. Small words before the verb show tense: ń (now), ti (already), máa (will), kò (not).",
    words: [
      w("lọ", "to go", "verb", "Mo lọ sí ilé.", "I went home."),
      w("wá", "to come", "verb", "Wá síbí.", "Come here."),
      w("jẹ", "to eat", "verb", "Mo jẹ ìrẹsì.", "I ate rice."),
      w("mu", "to drink", "verb", "Mo mu omi.", "I drank water."),
      w("rà", "to buy", "verb", "Mo rà ẹja.", "I bought fish."),
      w("tà", "to sell", "verb", "Ó ń tà ẹja.", "He/she is selling fish."),
      w("rí", "to see", "verb", "Mo rí ọ.", "I see you."),
      w("gbọ́", "to hear", "verb", "Mo gbọ́ ohùn rẹ.", "I hear your voice."),
      w("mọ̀", "to know", "verb", "Mi ò mọ̀.", "I don't know."),
      w("fẹ́", "to want; to like", "verb", "Mo fẹ́ omi.", "I want water."),
      w("sùn", "to sleep", "verb", "Mo sùn ní òru.", "I sleep at night."),
      w("jí", "to wake up", "verb", "Mo jí ní àárọ̀.", "I wake up in the morning."),
      w("kọ́", "to learn; to teach", "verb", "Mo ń kọ́ Yorùbá.", "I am learning Yoruba."),
      w("sọ", "to say; to speak", "verb", "Mo lè sọ Yorùbá díẹ̀.", "I can speak a little Yoruba."),
      w("kàwé", "to read", "verb", "Mo ń kàwé.", "I am reading."),
      w("kọ̀wé", "to write", "verb", "Mo ń kọ̀wé.", "I am writing."),
      w("ṣiṣẹ́", "to work", "verb", "Mo ń ṣiṣẹ́.", "I am working."),
      w("dúró", "to stand; to wait; to stop", "verb", "Dúró díẹ̀.", "Wait a little."),
      w("gbé", "to live; to carry", "verb", "Mo ń gbé ní Èkó.", "I live in Lagos."),
      w("lè", "can; to be able to", "verb", "Mo lè wá.", "I can come."),
      w("ń", "is/am -ing (happening now)", "particle", "Mo ń jẹun.", "I am eating."),
      w("ti", "already (completed)", "particle", "Mo ti jẹun.", "I have eaten."),
      w("máa", "will; usually", "particle", "Mo máa lọ ní ọ̀la.", "I will go tomorrow."),
      w("kò", "not (negative)", "particle", "Kò wá.", "He/she did not come."),
    ],
    phrases: [
      p("Mo ń jẹun.", "I am eating."),
      p("Mo ti jẹun.", "I have eaten."),
      p("Mo máa lọ sí ọjà ní ọ̀la.", "I will go to the market tomorrow."),
      p("Mi ò mọ̀.", "I don't know."),
      p("Mi ò fẹ́.", "I don't want it."),
      p("Kò wá.", "He/she did not come."),
      p("Ó ń kàwé.", "He/she is reading."),
      p("Wọ́n ń bọ̀.", "They are coming."),
      p("Mo lè sọ Yorùbá díẹ̀.", "I can speak a little Yoruba."),
      p("Ṣé o gbọ́?", "Do you hear/understand?"),
      p("Ó yé mi.", "I understand."),
      p("Kò yé mi.", "I don't understand."),
      p("Ẹ sọ ọ́ lẹ́ẹ̀kan sí i.", "Please say it once more."),
    ],
  },
  {
    id: "questions", title: "Question words", emoji: "❓",
    blurb: "What, who, where, how many, how much. Yes/no questions start with ṣé.",
    words: [
      w("kí", "what", "question word", "Kí ni èyí?", "What is this?"),
      w("ta", "who", "question word", "Ta ni ó wà níbẹ̀?", "Who is there?"),
      w("báwo", "how", "question word", "Báwo ni o ṣe wà?", "How are you?"),
      w("mélòó", "how many", "question word", "Ẹyin mélòó ni o rà?", "How many eggs did you buy?"),
      w("èló", "how much (price)", "question word", "Èló ni ìrẹsì?", "How much is the rice?"),
      w("èwo", "which", "question word", "Èwo ni o fẹ́?", "Which one do you want?"),
      w("nígbà wo", "when", "question word", "Nígbà wo ni o máa wá?", "When will you come?"),
      w("ṣé", "(starts a yes/no question)", "particle", "Ṣé o wà dáadáa?", "Are you well?"),
      w("èyí", "this (one)", "pronoun", "Èyí dára.", "This one is good."),
      w("ìyẹn", "that (one)", "pronoun", "Ìyẹn dára.", "That one is good."),
    ],
    phrases: [
      p("Kí ni èyí?", "What is this?"),
      p("Ta ni èyí?", "Who is this?"),
      p("Ibo ni o ń lọ?", "Where are you going?"),
      p("Báwo ni o ṣe wà?", "How are you?"),
      p("Kí nìdí?", "Why?"),
      p("Ṣé o mọ̀?", "Do you know?"),
      p("Ṣé o ń bọ̀?", "Are you coming?"),
      p("Èwo ni o fẹ́?", "Which one do you want?"),
    ],
  },
];

/** Short beginner dialogues for Read. One sentence per line; the first item is the speaker. */
export const DIALOGUES = [
  {
    title: "Ní ọjà", en: "At the market",
    lines: [
      ["Ìyá Tọ́lá", "Ẹ káàsán.", "Good afternoon."],
      ["Adé", "Ẹ káàsán.", "Good afternoon."],
      ["Adé", "Èló ni ìrẹsì?", "How much is the rice?"],
      ["Ìyá Tọ́lá", "Ẹgbẹ̀rún náírà ni.", "It is a thousand naira."],
      ["Adé", "Ó dára.", "That is fine."],
      ["Adé", "Mo fẹ́ ra ìrẹsì àti ẹyin mẹ́fà.", "I want to buy rice and six eggs."],
      ["Ìyá Tọ́lá", "Ẹ ṣé.", "Thank you."],
      ["Adé", "Ẹ ṣé púpọ̀.", "Thank you very much."],
      ["Adé", "Ó dàbọ̀.", "Goodbye."],
    ],
  },
  {
    title: "Ìkíni", en: "Greeting an elder",
    lines: [
      ["Adé", "Ẹ káàárọ̀, Bàbá.", "Good morning, Father."],
      ["Bàbá Kẹ́mi", "Ẹ káàárọ̀, ọmọ mi.", "Good morning, my child."],
      ["Bàbá Kẹ́mi", "Ṣé àlàáfíà ni?", "Are you well?"],
      ["Adé", "Àlàáfíà ni, ẹ ṣé.", "I am well, thank you."],
      ["Adé", "Báwo ni ẹbí?", "How is the family?"],
      ["Bàbá Kẹ́mi", "Wọ́n wà dáadáa.", "They are fine."],
      ["Adé", "Ó dàbọ̀, Bàbá.", "Goodbye, Father."],
      ["Bàbá Kẹ́mi", "Ó dàbọ̀.", "Goodbye."],
    ],
  },
  {
    title: "Ìdílé mi", en: "My family",
    lines: [
      ["Tọ́lá", "Orúkọ mi ni Tọ́lá.", "My name is Tọ́lá."],
      ["Tọ́lá", "Mo ní arákùnrin kan àti arábìnrin kan.", "I have one brother and one sister."],
      ["Adé", "Inú mi dùn láti pàdé rẹ, Tọ́lá.", "I am glad to meet you, Tọ́lá."],
      ["Adé", "Ibo ni ẹbí rẹ ń gbé?", "Where does your family live?"],
      ["Tọ́lá", "Wọ́n ń gbé ní Èkó.", "They live in Lagos."],
      ["Adé", "Ṣé bàbá rẹ jẹ́ olùkọ́?", "Is your father a teacher?"],
      ["Tọ́lá", "Bẹ́ẹ̀ni, bàbá mi jẹ́ olùkọ́.", "Yes, my father is a teacher."],
      ["Tọ́lá", "Ìyá mi ń tà ẹja ní ọjà.", "My mother sells fish at the market."],
    ],
  },
  {
    title: "Nínú ọkọ̀", en: "In a car",
    lines: [
      ["Adé", "Ẹ káàsán.", "Good afternoon."],
      ["Awakọ̀", "Ẹ káàsán.", "Good afternoon."],
      ["Adé", "Mo fẹ́ lọ sí ọjà.", "I want to go to the market."],
      ["Awakọ̀", "Ẹ wọ ọkọ̀.", "Get in."],
      ["Adé", "Èló ni?", "How much is it?"],
      ["Awakọ̀", "Igba náírà ni.", "It is two hundred naira."],
      ["Adé", "Ó wọ́n jù.", "It is too expensive."],
      ["Adé", "Mo ní ọgọ́rùn-ún náírà.", "I have a hundred naira."],
      ["Awakọ̀", "Ó dára.", "That is fine."],
      ["Adé", "Dúró níbí.", "Stop here."],
      ["Adé", "Ẹ ṣé púpọ̀.", "Thank you very much."],
    ],
  },
].map((d) => ({
  title: nfc(d.title),
  en: d.en,
  lines: d.lines.map(([who, yo, en]) => ({ who: nfc(who), yo: nfc(yo), en })),
  body: d.lines.map(([who, yo]) => nfc(`${who}: ${yo}`)).join("\n"),
}));

for (const u of UNITS) {
  u.title = nfc(u.title);
}

export const unitById = (id) => UNITS.find((u) => u.id === id);
export const WEEKDAYS = ["Ọjọ́ Àìkú", "Ọjọ́ Ajé", "Ọjọ́ Ìṣẹ́gun", "Ọjọ́rú", "Ọjọ́bọ̀", "Ọjọ́ Ẹtì", "Ọjọ́ Àbámẹ́ta"].map(nfc); // Date.getDay() order
export const totalItems = () => UNITS.reduce((n, u) => n + u.words.length + u.phrases.length, 0);
